/*
 * This source file was generated by the Gradle 'init' task
 */
package me.LogosAcUmbra.trialCalculator;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class AppTest {
    @Test void sampleTest() {
        assertNotNull(1, "app should have a greeting");
    }
}
